FROM node:24-bullseye AS install-tools

RUN curl -fsSL https://gist.githubusercontent.com/DIO0550/dcc09dc9d2dcefceb9b0cda183e7ef8e/raw/pnpm-safe-chain-setup.sh | sh

# サブシェルで実行することで、環境変数を引き継ぐ
RUN /bin/bash -i -c "curl -fsSL https://gist.githubusercontent.com/DIO0550/148b1392cf435ba3562da0d398bee442/raw/install-ai-tools.sh | sh"



FROM rust:1-trixie
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     pkg-config \
     libssl-dev \
     zip \
     unzip \
     nodejs \
     npm \
  && useradd -m -s /bin/bash vscode \
  && mkdir -p /workspaces \
  && mkdir -p /usr/local/cargo/registry /usr/local/cargo/git \
  && chown -R vscode:vscode /workspaces /usr/local/cargo \
  && rm -rf /var/lib/apt/lists/*


USER vscode
RUN curl 